apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  name: lightspeed-operator-catalog
  namespace: openshift-marketplace
spec:
  displayName: LightSpeed Operator
  sourceType: grpc
  secrets:
    - xrajesh-pull-secret
  image: quay.io/xrajesh/lightspeed-operator-catalog@sha256:705de93a17a95bf881a9fd065fb3826686910f46dc78d2edc8eba94a7d762134 
  updateStrategy:
    registryPoll:
      interval: 10m
