apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: |-
      [
        {
          "apiVersion": "ols.openshift.io/v1alpha1",
          "kind": "OLSConfig",
          "metadata": {
            "labels": {
              "app.kubernetes.io/created-by": "lightspeed-operator",
              "app.kubernetes.io/instance": "olsconfig-sample",
              "app.kubernetes.io/managed-by": "kustomize",
              "app.kubernetes.io/name": "olsconfig",
              "app.kubernetes.io/part-of": "lightspeed-operator"
            },
            "name": "olsconfig-sample"
          },
          "spec": {
            "llm": {
              "providers": [
                {
                  "credentialsSecretRef": {
                    "name": "credentials"
                  },
                  "models": [
                    {
                      "name": "gpt-3.5-turbo-1106"
                    }
                  ],
                  "name": "OpenAI"
                }
              ]
            }
          }
        }
      ]
    capabilities: Basic Install
    createdAt: "2024-02-24T13:31:26Z"
    operators.operatorframework.io/builder: operator-sdk-v1.33.0
    operators.operatorframework.io/project_layout: go.kubebuilder.io/v4
    operatorframework.io/cluster-monitoring: "true"
    operatorframework.io/suggested-namespace: openshift-lightspeed
  name: lightspeed-operator.v0.0.32
  namespace: openshift-lightspeed
spec:
  apiservicedefinitions: {}
  customresourcedefinitions:
    owned:
    - description: OLSConfig is the Schema for the olsconfigs API
      displayName: OLSConfig
      kind: OLSConfig
      name: olsconfigs.ols.openshift.io
      version: v1alpha1
  description: OpenShift LightSpeed (OLS) is an AI powered assistant that runs on
    OpenShift and provides answers to product questions using backend LLM services.
  displayName: Openshift Lightspeed
  icon:
  - base64data: ""
    mediatype: ""
  install:
    spec:
      clusterPermissions:
      - rules:
        - apiGroups:
          - apps
          resources:
          - deployments
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - ""
          resources:
          - configmaps
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - ""
          resources:
          - serviceaccounts
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - ""
          resources:
          - services
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - ols.openshift.io
          resources:
          - olsconfigs
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - ols.openshift.io
          resources:
          - olsconfigs/finalizers
          verbs:
          - update
        - apiGroups:
          - ols.openshift.io
          resources:
          - olsconfigs/status
          verbs:
          - get
          - patch
          - update
        - apiGroups:
          - authentication.k8s.io
          resources:
          - tokenreviews
          verbs:
          - create
        - apiGroups:
          - authorization.k8s.io
          resources:
          - subjectaccessreviews
          verbs:
          - create
        serviceAccountName: lightspeed-operator-controller-manager
      deployments:
      - label:
          app.kubernetes.io/component: manager
          app.kubernetes.io/created-by: lightspeed-operator
          app.kubernetes.io/instance: controller-manager
          app.kubernetes.io/managed-by: kustomize
          app.kubernetes.io/name: deployment
          app.kubernetes.io/part-of: lightspeed-operator
          control-plane: controller-manager
        name: lightspeed-operator-controller-manager
        spec:
          replicas: 1
          selector:
            matchLabels:
              control-plane: controller-manager
          strategy: {}
          template:
            metadata:
              annotations:
                kubectl.kubernetes.io/default-container: manager
              labels:
                control-plane: controller-manager
            spec:
              containers:
              - args:
                - --health-probe-bind-address=:8081
                - --metrics-bind-address=127.0.0.1:8080
                - --leader-elect
                - --images=lightspeed-service=quay.io/openshift/lightspeed-service-api:latest
                command:
                - /manager
                env:
                - name: WATCH_NAMESPACE
                  valueFrom:
                    fieldRef:
                      fieldPath: metadata.annotations['olm.targetNamespaces']
                image: quay.io/openshift/lightspeed-operator@sha256:c27acc1d6db151d9f463c8e0936356724f3e57cee4f358b82478b056b6b61377
                livenessProbe:
                  httpGet:
                    path: /healthz
                    port: 8081
                  initialDelaySeconds: 15
                  periodSeconds: 20
                name: manager
                readinessProbe:
                  httpGet:
                    path: /readyz
                    port: 8081
                  initialDelaySeconds: 5
                  periodSeconds: 10
                resources:
                  limits:
                    cpu: 500m
                    memory: 128Mi
                  requests:
                    cpu: 10m
                    memory: 64Mi
                securityContext:
                  allowPrivilegeEscalation: false
                  capabilities:
                    drop:
                    - ALL
              - args:
                - --secure-listen-address=0.0.0.0:8443
                - --upstream=http://127.0.0.1:8080/
                - --logtostderr=true
                - --v=0
                image: gcr.io/kubebuilder/kube-rbac-proxy:v0.14.1
                name: kube-rbac-proxy
                ports:
                - containerPort: 8443
                  name: https
                  protocol: TCP
                resources:
                  limits:
                    cpu: 500m
                    memory: 128Mi
                  requests:
                    cpu: 5m
                    memory: 64Mi
                securityContext:
                  allowPrivilegeEscalation: false
                  capabilities:
                    drop:
                    - ALL
              securityContext:
                runAsNonRoot: true
              serviceAccountName: lightspeed-operator-controller-manager
              terminationGracePeriodSeconds: 10
      permissions:
      - rules:
        - apiGroups:
          - ""
          resources:
          - configmaps
          verbs:
          - get
          - list
          - watch
          - create
          - update
          - patch
          - delete
        - apiGroups:
          - coordination.k8s.io
          resources:
          - leases
          verbs:
          - get
          - list
          - watch
          - create
          - update
          - patch
          - delete
        - apiGroups:
          - ""
          resources:
          - events
          verbs:
          - create
          - patch
        serviceAccountName: lightspeed-operator-controller-manager
    strategy: deployment
  installModes:
  - supported: false
    type: OwnNamespace
  - supported: false
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: true
    type: AllNamespaces
  keywords:
  - ai
  - assistant
  - llm
  - openshift
  links:
  - name: Lightspeed Operator
    url: https://lightspeed-operator.domain
  maturity: alpha
  provider:
    name: Red Hat, Inc
    url: https://github.com/openshift/lightspeed-service
  version: 0.0.32
