apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: '[]'
    capabilities: Basic Install
  name: lightspeed-operator.v0.0.0
  namespace: placeholder
spec:
  apiservicedefinitions: {}
  customresourcedefinitions:
    owned:
    - description: OLSConfig is the Schema for the olsconfigs API
      displayName: OLSConfig
      kind: OLSConfig
      name: olsconfigs.ols.openshift.io
      version: v1alpha1
  description: OpenShift LightSpeed (OLS) is an AI powered assistant that runs on
    OpenShift and provides answers to product questions using backend LLM services.
  displayName: Openshift Lightspeed
  icon:
  - base64data: ""
    mediatype: ""
  install:
    spec:
      deployments: null
    strategy: ""
  installModes:
  - supported: false
    type: OwnNamespace
  - supported: false
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: true
    type: AllNamespaces
  keywords:
  - ai
  - assistant
  - llm
  - openshift
  links:
  - name: Lightspeed Operator
    url: https://lightspeed-operator.domain
  maturity: alpha
  provider:
    name: Red Hat, Inc
    url: https://github.com/openshift/lightspeed-service
  version: 0.0.0
